/* tslint:disable */
/* eslint-disable */
/**
 * Gentrace API
 * These API routes are designed to ingest events from clients.
 *
 * The version of the OpenAPI document: 0.23.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setClientTokenToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateFeedbackV2 } from '../models';
// @ts-ignore
import { FeedbackV2 } from '../models';
// @ts-ignore
import { UpdateFeedbackV2 } from '../models';
/**
 * V2Api - axios parameter creator
 * @export
 */
export const V2ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get feedback
         * @param {string} id Feedback ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2FeedbackIdGet: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v2FeedbackIdGet', 'id', id)
            const localVarPath = `/v2/feedback/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update feedback
         * @param {string} id Feedback ID
         * @param {UpdateFeedbackV2} updateFeedbackV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2FeedbackIdPatch: async (id: string, updateFeedbackV2: UpdateFeedbackV2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('v2FeedbackIdPatch', 'id', id)
            // verify required parameter 'updateFeedbackV2' is not null or undefined
            assertParamExists('v2FeedbackIdPatch', 'updateFeedbackV2', updateFeedbackV2)
            const localVarPath = `/v2/feedback/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateFeedbackV2, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create feedback
         * @param {CreateFeedbackV2} createFeedbackV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2FeedbackPost: async (createFeedbackV2: CreateFeedbackV2, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createFeedbackV2' is not null or undefined
            assertParamExists('v2FeedbackPost', 'createFeedbackV2', createFeedbackV2)
            const localVarPath = `/v2/feedback`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createFeedbackV2, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * V2Api - functional programming interface
 * @export
 */
export const V2ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = V2ApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get feedback
         * @param {string} id Feedback ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2FeedbackIdGet(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FeedbackV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v2FeedbackIdGet(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update feedback
         * @param {string} id Feedback ID
         * @param {UpdateFeedbackV2} updateFeedbackV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2FeedbackIdPatch(id: string, updateFeedbackV2: UpdateFeedbackV2, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FeedbackV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v2FeedbackIdPatch(id, updateFeedbackV2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Create feedback
         * @param {CreateFeedbackV2} createFeedbackV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async v2FeedbackPost(createFeedbackV2: CreateFeedbackV2, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FeedbackV2>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.v2FeedbackPost(createFeedbackV2, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * V2Api - factory interface
 * @export
 */
export const V2ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = V2ApiFp(configuration)
    return {
        /**
         * 
         * @summary Get feedback
         * @param {string} id Feedback ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2FeedbackIdGet(id: string, options?: any): AxiosPromise<FeedbackV2> {
            return localVarFp.v2FeedbackIdGet(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update feedback
         * @param {string} id Feedback ID
         * @param {UpdateFeedbackV2} updateFeedbackV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2FeedbackIdPatch(id: string, updateFeedbackV2: UpdateFeedbackV2, options?: any): AxiosPromise<FeedbackV2> {
            return localVarFp.v2FeedbackIdPatch(id, updateFeedbackV2, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create feedback
         * @param {CreateFeedbackV2} createFeedbackV2 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        v2FeedbackPost(createFeedbackV2: CreateFeedbackV2, options?: any): AxiosPromise<FeedbackV2> {
            return localVarFp.v2FeedbackPost(createFeedbackV2, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * V2Api - object-oriented interface
 * @export
 * @class V2Api
 * @extends {BaseAPI}
 */
export class V2Api extends BaseAPI {
    /**
     * 
     * @summary Get feedback
     * @param {string} id Feedback ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V2Api
     */
    public v2FeedbackIdGet(id: string, options?: AxiosRequestConfig) {
        return V2ApiFp(this.configuration).v2FeedbackIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update feedback
     * @param {string} id Feedback ID
     * @param {UpdateFeedbackV2} updateFeedbackV2 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V2Api
     */
    public v2FeedbackIdPatch(id: string, updateFeedbackV2: UpdateFeedbackV2, options?: AxiosRequestConfig) {
        return V2ApiFp(this.configuration).v2FeedbackIdPatch(id, updateFeedbackV2, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create feedback
     * @param {CreateFeedbackV2} createFeedbackV2 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof V2Api
     */
    public v2FeedbackPost(createFeedbackV2: CreateFeedbackV2, options?: AxiosRequestConfig) {
        return V2ApiFp(this.configuration).v2FeedbackPost(createFeedbackV2, options).then((request) => request(this.axios, this.basePath));
    }
}
